//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf_ferma
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horse_health
    {
        public int ID { get; set; }
        public Nullable<int> ID_Horse { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> Body_mass_index { get; set; }
        public Nullable<double> Body_temperature { get; set; }
        public string Dental_condition { get; set; }
        public Nullable<System.DateTime> DataReport { get; set; }
    
        public virtual Horse Horse { get; set; }
    }
}
