//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf_ferma
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KumysEntities : DbContext
    {
        public KumysEntities()
            : base("name=KumysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Horse> Horse { get; set; }
        public virtual DbSet<Horse_health> Horse_health { get; set; }
        public virtual DbSet<Retail_Network> Retail_Network { get; set; }
        public virtual DbSet<Sorting_Center> Sorting_Center { get; set; }
        public virtual DbSet<Sorting_Center_report_> Sorting_Center_report_ { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<The_can> The_can { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
