//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf_ferma
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sorting_Center_report_
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> Number_of_cans_delivered { get; set; }
        public Nullable<int> Average_product_temperature { get; set; }
        public Nullable<int> Average_coagulability__as_a___ { get; set; }
        public Nullable<int> ID_Sorting_Center { get; set; }
    
        public virtual Sorting_Center Sorting_Center { get; set; }
    }
}
