//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf_ferma
{
    using System;
    using System.Collections.Generic;
    
    public partial class The_can
    {
        public int ID { get; set; }
        public Nullable<int> ID_Horse { get; set; }
        public Nullable<int> ID_Retail_network { get; set; }
        public Nullable<int> ID_Sorting_Center { get; set; }
        public string Volume_of_the_can { get; set; }
    
        public virtual Horse Horse { get; set; }
        public virtual Retail_Network Retail_Network { get; set; }
    }
}
